# Generated by Django 3.2.7 on 2021-09-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazzboardapi', '0005_auto_20210920_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='jazzboardapi.comment'),
        ),
    ]
