# Generated by Django 3.2.7 on 2021-09-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazzboardapi', '0006_comment_tocomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comComment',
        ),
    ]
