# Generated by Django 3.2.8 on 2021-11-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazzboardapi', '0008_auto_20210930_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
